# Generated by Django 3.2 on 2021-07-03 11:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0013_rename_watchlater_listenlater'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Listenlater',
            new_name='Watchlater',
        ),
    ]
